### ISSUE TITLE
DoS Attack

### ISSUE THREAD

**Issue by fredriksvantes** [ethereum/public-disclosures#28]
UID: CL-2020-03

Severity: high

Type: DoS

Affected Clients: Teku

Summary: Teku nodes are vulnerable to a simple DoS attack that prevents them from participating in consensus.

Links: https://github.com/ethereum/public-attacknets/issues/7

Reported: 2020-07-26

Fixed: 2020-07-31

Published: 2021-12-01

Bounty Hunter: Jonny Rhea

Bounty Points: 1250

**Comment by jrhea** [comment]
This attack took down the attacknet. I don't see why it's only worth 1250 point?

**Comment by fredriksvantes** [comment]
Hey @jrhea , I'm following up this in the same way as in https://github.com/ethereum/public-disclosures/issues/29
