### ISSUE TITLE
DoS Attack

### ISSUE THREAD

**Issue by fredriksvantes** [ethereum/public-disclosures#29]
UID: CL-2020-02

Severity: high

Type: DoS

Affected Clients: Prysm

Summary: Prysm nodes are vulnerable to a DoS attack that prevents them from participating in consensus.

Links: https://github.com/ethereum/public-attacknets/issues/12

Reported: 2020-07-01

Fixed: 2020-08-06

Published: 2021-12-01

Bounty Hunter: Jonny Rhea

Bounty Points: 1250

**Comment by jrhea** [comment]
Why was this only worth 1250 points? I uncovered a 9 year old bug in Go. 

https://groups.google.com/forum/#!msg/golang-announce/NyPIaucMgXo/GdsyQP6QAAAJ

**Comment by fredriksvantes** [comment]
Hi Jonny,

The vulnerabilities found during the attacknet phase (pre-beaconchain launch) were given low amounts of USD as the clients were still nascent. When compiling the bounty list, the payments made for each bounty was divided by 2 as that's the current standard (1 point equals 2 USD). I do however notice that the amount of points (8000) in the vulnerability sheet does not match up to the total points you have on the bounty board (15500) so I will do a bit of digging to figure out the points that were correct for each of the vulnerabilities you submitted. Thank you for making this visible!

**Comment by jrhea** [comment]
Thanks for looking into this.  A couple of notes:

1) Understood that the bounties we're worth less. I will say that a 9 year old bug in a Go std library probably warrants full credit, right?

2) #25 is actually 3 separate attacks and resulted any many client fixes

3) #23 and #24 were actually duplicates of attacks I already submitted. Strangely they got full cred. Also, #27 got full credit and took place during the attacknets so there does seem to be some inconsistency.


Anyways, you all are great... I just like points. 🫶
